name: weather_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  dio: ^5.3.3
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.6
  fpdart: ^1.1.0
  google_sign_in: ^6.1.6
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
